version: '1.0'
services:
  redis-server-1:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - my-network
    
  api-server-1:
    image: khanhtrn2608/idx_pj_nest_1:latest
    ports:
      - 3009:3009
    depends_on:
      - redis-server-1
    networks:
      - my-network

    environment:
      - APP_HOST=localhost
      - APP_PORT=3001
      - APP_API_DOCUMENT=true

      - DB_HOST=103.72.96.54
      - DB_PORT=5432
      - DB_USERNAME=khanhtn
      - DB_PASSWORD=kh@nh124
      - DB_DATABASE=dbs_personal

      - REDIS_HOST=redis-server-1
      - REDIS_PORT=6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=

      - S3_REGION=auto
      - S3_ACCOUNT_ID=23724040a0d3b2352e589b36b69d8437
      - S3_ACCESS_KEY_ID=30dfdd58f5adf2d9a51b2926aae9fd0a
      - S3_SECRET_ACCESS_KEY=741cac77745b929653e233a429fcc57cdfcf09feda715f81956f61f451afdb9d

      - R2_BUCKET_URL=https://pub-a877d90e2f2844dab75958f2f82dfd6b.r2.dev

networks:
  my-network:
    driver: bridge